eternal_ascension = {
    'image_generation':
    [
       {
"0": "A moonlit clearing in a dense forest, with an ancient stone altar at its center, bathed in an otherworldly blue glow, surrounded by swirling mist.",
"90": "A dimly lit cave, adorned with intricate, glowing runes on the walls, leading to a hidden chamber filled with ancient scrolls and relics, emitting an eerie green light.",
"180": "A tranquil waterfall in a secluded valley, shrouded in mist, with rainbow-colored water droplets glistening in the air, reflecting the rays of a setting sun.",
"270": "A serene lake nestled in the heart of a mountain range, with crystal-clear water reflecting the stars in the night sky, and an ancient shrine standing at its shore, emanating a soft, golden light.",
"360": "A forgotten temple atop a mist-covered mountain peak, with ornate carvings depicting mythical creatures and divine beings, and a flickering torch casting shadows on the walls, revealing cryptic symbols.",
"450": "A mystical grove of ancient trees, with gnarled branches reaching towards the heavens, adorned with glowing orbs that pulsate with otherworldly energy, casting an ethereal light on the forest floor.",
"540": "A hidden cave entrance behind a cascading waterfall, revealing a secret passage lined with shimmering crystals, leading to a chamber filled with ancient relics and a glowing, floating orb that radiates with a mesmerizing aura.",
"630": "An abandoned castle on a moonlit cliff overlooking a stormy sea, with crumbling walls adorned with faded murals depicting a long-forgotten ritual, and a solitary, glowing brazier flickering in the darkness.",
"720": "A mystical desert oasis, with a pool of shimmering water reflecting the stars in the night sky, surrounded by palm trees adorned with glowing gemstones that emit a captivating, otherworldly light.",
"810": "A mysterious cave with a bottomless abyss, filled with swirling mist that reveals glimpses of a hidden realm, with ancient runes etched on the walls, glowing with a pulsating, eerie light.",
"900": "A serene garden at the heart of a sacred temple, with vibrant flowers in bloom, emitting a soft, radiant light, and a serene pond reflecting the moon, surrounded by ancient statues of mythical beasts.",
"990": "A mystical forest glade, with ancient stone pillars adorned with glowing runes, and a pool of shimmering water at its center, reflecting a full moon that casts an ethereal glow on the surroundings.",
"1080": "A secluded cave entrance hidden behind a waterfall, with a glowing portal crackling with arcane energy, revealing a mysterious realm filled with floating islands and glowing crystals, emanating a mesmerizing, otherworldly light.",
"1170": "An ancient stone circle atop a mist-shrouded hill, with standing stones adorned with glowing symbols, and a portal to a hidden chamber at its center, emitting a pulsating, otherworldly light.",
"1260": "A mystical glen with ancient ruins adorned with glowing sigils, and a portal to another realm, emanating a brilliant, blinding light, casting shadows that dance to an otherworldly rhythm.",
"1350": "A forgotten temple hidden deep within a dense jungle, with a crumbling entrance guarded by ancient statues, and a grand chamber with a towering altar bathed in a celestial light, radiating with unimaginable power.",
"1440": "A serene meadow atop a mountain peak, with wildflowers in bloom, and a solitary, ancient tree at its center, adorned with glowing crystals that emit a soothing, ethereal light.",
"1530": "A hidden cave behind a veil of waterfalls, revealing a chamber adorned with ancient relics and glowing crystals, casting a surreal, otherworldly light on the walls, with faint whispers echoing in the air, hinting at long-forgotten secrets of immortality.",
"1620": "A mystical cavern filled with glowing stalactites and stalagmites, with a subterranean lake reflecting a multitude of colors, and an ancient altar at its center, exuding a mysterious, pulsating light.",
"1710": "A secluded grove at the heart of a enchanted forest, with ancient trees adorned with shimmering leaves that emit a soft, mystical light, and a tranquil pool of water reflecting the moon, surrounded by glowing flowers.",
"1800": "A sacred shrine hidden within a labyrinthine cave, with walls adorned with ancient murals depicting a ritual of immortality, and a mysterious, glowing crystal at the center, radiating a captivating, otherworldly glow.",
"1890": "A mystical underwater grotto, with bioluminescent corals emitting a dazzling array of colors, and an ancient statue of a mermaid holding a glowing pearl that glows with a radiant, ethereal light.",
"1980": "A hidden chamber within an ancient pyramid, adorned with intricate hieroglyphs and glowing gems, revealing a sarcophagus bathed in a mystical, golden light, with whispers of ancient incantations echoing in the air.",
"2070": "A serene, snowy landscape with an ancient ice cave, emanating a soft, blue light from within, revealing frozen stalactites and stalagmites adorned with glowing runes, telling the tale of an ancient ritual of immortality.",
"2160": "A sacred, misty waterfall hidden within a dense forest, with a hidden cave behind the cascading waters, revealing an altar adorned with glowing crystals, radiating a mesmerizing, otherworldly light, beckoning the chosen one to unlock the secrets of eternal life.",
"2250": "A mystical, celestial realm with floating islands adorned with glowing flowers and ancient ruins, with a grand palace at its center, exuding a brilliant, blinding light, where the immortals gather to perform the age-old ritual of immortality, shrouded in mystery and magic."
},
{
"0": "A moonlit forest clearing, with ancient, towering trees casting eerie shadows. The ground is covered in a thick layer of fog, concealing what lurks within. The air is still, and the only sound is the distant howl of a lone wolf.",
"90": "A misty lake shrouded in darkness, surrounded by jagged cliffs. The water is still and reflects the moonlight, revealing a faint silhouette of a mysterious creature lurking just below the surface. The air is heavy with anticipation, as if something otherworldly is about to emerge.",
"180": "A crumbling, overgrown castle atop a hill, overlooking a desolate valley. The castle is surrounded by an impenetrable mist, and its turrets are silhouetted against a blood-red sky. A sense of foreboding hangs in the air, as if the castle holds dark secrets and ancient curses.",
"270": "A desolate wasteland covered in ash and debris, with charred trees and broken structures scattered about. The sky is a swirling mass of dark clouds, and bolts of lightning periodically illuminate the bleak landscape. There is no sign of life, only an overwhelming sense of desolation and despair.",
"360": "A mysterious cave entrance hidden deep in a dense forest, adorned with ancient runes and symbols. The entrance is guarded by a pair of glowing, red eyes that seem to be watching, unblinking. The darkness within the cave seems to stretch infinitely, concealing untold horrors and ancient mysteries.",
"450": "A dilapidated, abandoned village nestled in a valley, with crumbling buildings and cobweb-covered streets. The village is surrounded by a thick mist that obscures what lies beyond, and eerie whispers seem to emanate from the shadows. The air is heavy with a sense of loss and tragedy.",
"540": "A desolate graveyard covered in overgrown weeds and tombstones, with a pale moon casting eerie shadows. The gravestones bear ancient inscriptions and symbols, and the mist seems to swirl with otherworldly energy. The atmosphere is chilling, as if the souls of the departed still linger, trapped in an eternal realm between worlds.",
"630": "A mist-shrouded, ancient ruin of a forgotten civilization, with crumbling pillars and cracked statues. The air is heavy with the echoes of lost souls, and the shadows seem to dance with unseen entities. The ruins hold untold secrets and forbidden knowledge, whispering of ancient truths that humankind was never meant to discover.",
"720": "A deep, dark forest with gnarled trees and twisted roots that seem to writhe and grasp at the air. The forest is bathed in an otherworldly, ethereal light that seems to come from within the trees themselves. Strange, glowing orbs hover in the air, casting an eerie glow on the forest floor. The sense of being watched by unseen eyes is palpable, and the fear of the unknown lingers in the air.",
"810": "A desolate, abandoned asylum on a hill, with broken windows and crumbling walls. The asylum is surrounded by a dense fog that seems to swallow all sound and movement. Strange, ghostly apparitions flicker in and out of existence, and the air is heavy with the echoes of lost souls. The asylum holds the remnants of tortured memories and unspeakable horrors, a testament to the darkest fears of humankind.",
"900": "A misty, moonlit marshland with twisted trees and murky waters. Strange, bioluminescent plants cast an eerie glow on the surroundings, revealing glimpses of mysterious creatures lurking just below the surface. The air is heavy with the scent of decay and the calls of unknown creatures. The marshland holds a sense of otherworldly mystique, as if ancient spirits and creatures of the night lurk in its depths, ready to emerge and haunt the dreams of those who dare to venture too close.",
"990": "A desolate, abandoned cathedral in the midst of a dense forest, with towering spires and stained glass windows that seem to emit a faint, ghostly light. The interior is shrouded in darkness, and the air is thick with the smell of incense and candle wax. Shadows dance on the walls, as if driven by unseen forces, and whispers echo through the halls, speaking of long-forgotten sins and unfathomable horrors.",
"1080": "A mist-covered, ancient stone circle atop a windswept hill, with weathered stones that seem to emanate an otherworldly energy. The air crackles with a sense of power and foreboding, as if the circle holds the key to unlocking ancient mysteries and tapping into primal fears. The mist seems to part at the center, revealing a dark, gaping hole that seems to lead to an abyss of infinite darkness.",
"1170": "A moonlit, deserted beach with black sand and crashing waves. The air is heavy with the smell of salt and seaweed, and the sound of the ocean seems to echo with the whispers of lost souls. Strange, otherworldly creatures emerge from the depths of the sea, with glowing eyes and sinister grins, as if the ocean itself is a portal to a realm of nightmares and fears.",
"1260": "A dense, fog-shrouded swamp with twisted trees and murky waters that seem to conceal unspeakable horrors. The air is heavy with the scent of decay and the sounds of unseen creatures slithering through the muck. Strange, glowing fungi and flowers emit an eerie light, revealing glimpses of grotesque creatures lurking in the shadows. The swamp is a realm of darkness and mystery, where ancient fears come to life.",
"1350": "A desolate, crumbling castle atop a cliff overlooking a stormy sea. The castle is enveloped in a thick mist that seems to seep from its very walls. The sky is illuminated by lightning, revealing glimpses of ghostly apparitions that seem to be trapped within the castle's ancient walls. The air is heavy with the echoes of lost souls and the whispers of dark secrets that the castle holds.",
"1440": "A moonlit, overgrown graveyard with cracked tombstones and tangled ivy. The gravestones bear ancient inscriptions and symbols, and the air is thick with a sense of loss and sorrow. Shadows dance among the graves, as if the spirits of the departed are restless, seeking eternal rest. The moon casts an ethereal light on the scene, revealing glimpses of phantom figures and mysterious symbols etched into the ground.",
"1530": "A misty, ancient forest with towering trees and a thick carpet of fallen leaves. The air is heavy with the scent of damp earth and decaying vegetation. Strange, glowing mushrooms and plants emit an otherworldly light, casting eerie shadows on the forest floor. The trees seem to whisper with ancient knowledge and hidden truths, and the forest holds a sense of primal fear that seems to seep into the very soul.",
"1620": "A desolate, abandoned village nestled in a valley, with crumbling buildings and empty streets. The village is enveloped in an impenetrable mist that seems to trap those who venture too close. Strange, ghostly apparitions flicker in and out of existence, whispering incoherent words and beckoning with phantom hands. The air is heavy with the echoes of lost lives and forgotten fears.",
"1710": "A moonlit, abandoned carnival with rusted rides and decaying tents, as if frozen in time. The air is filled with a sense of foreboding and echoes of laughter from long ago. The carousel spins slowly, revealing faded, peeling paint and empty seats that seem to beckon with a sense of eerie nostalgia. The once bright lights of the Ferris wheel now cast haunting shadows, and the distorted mirrors of the funhouse reflect distorted images that seem to distort reality itself.",
"1800": "A mist-shrouded, ancient ruins of a forgotten civilization, with crumbling stone pillars and a sense of eerie silence. The air is thick with the whispers of lost souls and echoes of ancient chants. Strange symbols and markings adorn the walls, hinting at long-forgotten rituals and forbidden knowledge. The ruins hold a sense of mystery and dread, as if the ghosts of the past still linger, guarding their secrets with malevolent intent.",
"1890": "A moonlit, deserted graveyard with weathered tombstones and gnarled trees that cast eerie shadows. The mist hangs low, obscuring the graves and creating an atmosphere of otherworldly mystery. Strange, ethereal lights flicker among the tombstones, revealing glimpses of ghostly apparitions and mysterious symbols etched into the stones. The air is heavy with the scent of damp earth and the whispers of restless spirits, as if the graveyard holds the key to unlocking ancient fears.",
"1980": "A dense, fog-filled forest with twisted branches and a sense of palpable darkness. The trees seem to loom overhead, casting long shadows that seem to reach out with sinister intent. The mist swirls and shifts, creating a sense of disorientation and trepidation. Strange, glowing eyes peer out from the darkness, and eerie sounds echo through the trees. The forest is a realm of primal fears, where ancient nightmares come to life.",
"2070": "A moonlit, desolate moorland with rocky outcrops and a sense of desolation. The air is heavy with the scent of heather and damp earth, and the wind howls with an otherworldly intensity. Strange, flickering lights dance across the moor, revealing glimpses of ghostly apparitions and mysterious symbols etched into the stones. The moor holds a sense of ancient mystique, as if the spirits of the land are restless and seeking vengeance.",
"2160": "A mist-shrouded, ancient temple atop a mountain peak, with crumbling stone steps and intricate carvings that hint at a forgotten history. The air is heavy with the scent of incense and the echoes of long-forgotten prayers. Strange, glowing symbols and artifacts emit an otherworldly light, revealing glimpses of shadowy figures and mysterious portals. The temple holds a sense of foreboding and awe, as if the secrets of the universe are hidden within its walls.",
"2250": "A moonlit, deserted castle with ivy-covered walls and broken windows that seem to peer into darkness. The castle stands atop a hill, overlooking a mist-filled valley that seems to stretch into infinity. The air is heavy with the echoes of lost souls and the whispers of ancient fears. Strange, ghostly apparitions flicker in and out of existence, hinting at the horrors that lie within the castle's walls. The moon casts a pale light on the scene, revealing glimpses of hidden passages and forbidden chambers, where the fears of humankind are brought to life."
}



    ],
    'music_name': 
        [
            'eternal_ascension',
            'mystical_visions'
        ],
    'n_frames_music':
        [   
            150,
            150

        ]
}