M000001 = {
    'image_generation':
    [
        {
            "0": "A neon-colored abstract cityscape with towering buildings and flashing lights. The only sign of life is a lone figure in the distance.",
            "90": "A kaleidoscope of shapes and colors twisting and morphing into each other in a mesmerizing display.",
            "180": "An intricate network of glowing circuits and wires pulsing with energy, almost like a living organism.",
            "270": "A vast, empty space with a single object in the center - a glowing orb that seems to be drawing all the energy and light towards it.",
            "360": "A pulsating, throbbing mass of energy that seems to be growing and expanding, almost like a living creature.",
            "450": "A glitchy, distorted world where the laws of physics no longer apply. Shapes and colors warp and contort in impossible ways.",
            "540": "A matrix of intersecting lines and shapes that seem to be forming a giant, abstract spiderweb.",
            "630": "A swirling vortex of color and sound, drawing everything in its path towards a central point.",
            "720": "A labyrinthine maze of glowing tunnels and passages, with no clear end in sight.",
            "810": "A cityscape seen from above, with neon lights and flickering signs creating a mesmerizing display.",
            "900": "A psychedelic forest of towering, luminescent trees and strange, otherworldly creatures.",
            "990": "A vast, empty desert landscape, with nothing but sand and sky as far as the eye can see.",
            "1080": "A chaotic, glitchy world where reality is constantly shifting and changing, and nothing can be trusted.",
            "1170": "A dark, foreboding cave system, filled with strange, glowing crystals and ominous shadows.",
            "1260": "A neon-colored rollercoaster that twists and turns through a futuristic cityscape.",
            "1350": "A shimmering, translucent ocean filled with strange, alien life forms.",
            "1440": "A towering, futuristic cityscape that seems to go on forever, with flashing lights and neon signs as far as the eye can see.",
            "1530": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "1620": "A vast, empty space filled with slowly moving clouds of gas and dust.",
            "1710": "A kaleidoscope of shapes and colors that seem to be forming a giant, abstract mandala.",
            "1800": "A dark, stormy night sky filled with flashing bolts of lightning and ominous clouds.",
            "1890": "A strange, otherworldly landscape filled with bizarre rock formations and surreal vistas.",
            "1980": "A distorted, glitchy version of reality where nothing is quite as it seems.",
            "2070": "A surreal, dreamlike world filled with floating islands and strange, abstract shapes.",
            "2160": "A vast, empty desert landscape, with nothing but sand and sky as far as the eye can see.",
            "2250": "A towering, futuristic cityscape that seems to go on forever, with flashing lights and neon signs as far as the eye can see.",
            "2340": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "2430": "A dark, foreboding cave system, filled with strange, glowing crystals and ominous shadows.",
            "2520": "A shimmering, translucent ocean filled with strange, alien life forms.",
            "2610": "A chaotic, glitchy world where reality is constantly shifting and changing, and nothing can be trusted.",
            "2700": "A neon-colored rollercoaster that twists and turns through a futuristic cityscape.",
            "2790": "A kaleidoscope of shapes and colors that seem to be forming a giant, abstract mandala.",
            "2880": "A pulsating, throbbing mass of energy that seems to be growing and expanding, almost like a living creature.",
            "2970": "A vast, empty space with a single object in the center - a glowing orb that seems to be drawing all the energy and light towards it.",
            "3060": "An intricate network of glowing circuits and wires pulsing with energy, almost like a living organism.",
            "3150": "A surreal, dreamlike world filled with floating islands and strange, abstract shapes.",
            "3240": "A dark, stormy night sky filled with flashing bolts of lightning and ominous clouds.",
            "3330": "A neon-colored abstract cityscape with towering buildings and flashing lights. The only sign of life is a lone figure in the distance.",
            "3420": "A glitchy, distorted world where the laws of physics no longer apply. Shapes and colors warp and contort in impossible ways.",
            "3510": "A towering, futuristic cityscape that seems to go on forever, with flashing lights and neon signs as far as the eye can see.",
            "3600": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "3690": "A vast, empty space filled with slowly moving clouds of gas and dust.",
            "3780": "A strange, otherworldly landscape filled with bizarre rock formations and surreal vistas.",
            "3870": "A kaleidoscope of shapes and colors twisting and morphing into each other in a mesmerizing display.",
            "3960": "A dark, foreboding cave system, filled with strange, glowing crystals and ominous shadows.",
            "4050": "A shimmering, translucent ocean filled with strange, alien life forms.",
            "4140": "A chaotic, glitchy world where reality is constantly shifting and changing, and nothing can be trusted.",
            "4230": "A neon-colored rollercoaster that twists and turns through a futuristic cityscape.",
            "4320": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "4410": "A vast, empty space with a single object in the center - a glowing orb that seems to be drawing all the energy and light towards it.",
            "4500": "A psychedelic forest of towering, luminescent trees and strange, otherworldly creatures."
        },
        {
            "0": "A neon-colored cityscape with towering buildings and flashing lights. The only sign of life is a lone figure in the distance.",
            "90": "A kaleidoscope of shapes and colors twisting and morphing into each other in a mesmerizing display.",
            "180": "An intricate network of glowing circuits and wires pulsing with energy, almost like a living organism.",
            "270": "A vast, empty space with a single object in the center - a glowing orb that seems to be drawing all the energy and light towards it.",
            "360": "A pulsating, throbbing mass of energy that seems to be growing and expanding, almost like a living creature.",
            "450": "A glitchy, distorted world where the laws of physics no longer apply. Shapes and colors warp and contort in impossible ways.",
            "540": "A matrix of intersecting lines and shapes that seem to be forming a giant, abstract spiderweb.",
            "630": "A swirling vortex of color and sound, drawing everything in its path towards a central point.",
            "720": "A labyrinthine maze of glowing tunnels and passages, with no clear end in sight.",
            "810": "A cityscape seen from above, with neon lights and flickering signs creating a mesmerizing display.",
            "900": "A psychedelic forest of towering, luminescent trees and strange, otherworldly creatures.",
            "990": "A vast, empty desert landscape, with nothing but sand and sky as far as the eye can see.",
            "1080": "A chaotic, glitchy world where reality is constantly shifting and changing, and nothing can be trusted.",
            "1170": "A dark, foreboding cave system, filled with strange, glowing crystals and ominous shadows.",
            "1260": "A neon-colored rollercoaster that twists and turns through a futuristic cityscape.",
            "1350": "A shimmering, translucent ocean filled with strange, alien life forms.",
            "1440": "A towering, futuristic cityscape that seems to go on forever, with flashing lights and neon signs as far as the eye can see.",
            "1530": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "1620": "A vast, empty space filled with slowly moving clouds of gas and dust.",
            "1710": "A kaleidoscope of shapes and colors that seem to be forming a giant, abstract mandala.",
            "1800": "A dark, stormy night sky filled with flashing bolts of lightning and ominous clouds.",
            "1890": "A strange, otherworldly landscape filled with bizarre rock formations and surreal vistas.",
            "1980": "A distorted, glitchy version of reality where nothing is quite as it seems.",
            "2070": "A surreal, dreamlike world filled with floating islands and strange, abstract shapes.",
            "2160": "A vast, empty desert landscape, with nothing but sand and sky as far as the eye can see.",
            "2250": "A towering, futuristic cityscape that seems to go on forever, with flashing lights and neon signs as far as the eye can see.",
            "2340": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "2430": "A dark, foreboding cave system, filled with strange, glowing crystals and ominous shadows.",
            "2520": "A shimmering, translucent ocean filled with strange, alien life forms.",
            "2610": "A chaotic, glitchy world where reality is constantly shifting and changing, and nothing can be trusted.",
            "2700": "A neon-colored rollercoaster that twists and turns through a futuristic cityscape.",
            "2790": "A kaleidoscope of shapes and colors that seem to be forming a giant, abstract mandala.",
            "2880": "A pulsating, throbbing mass of energy that seems to be growing and expanding, almost like a living creature.",
            "2970": "A vast, empty space with a single object in the center - a glowing orb that seems to be drawing all the energy and light towards it.",
            "3060": "An intricate network of glowing circuits and wires pulsing with energy, almost like a living organism.",
            "3150": "A surreal, dreamlike world filled with floating islands and strange, abstract shapes.",
            "3240": "A dark, stormy night sky filled with flashing bolts of lightning and ominous clouds.",
            "3330": "A neon-colored abstract cityscape with towering buildings and flashing lights. The only sign of life is a lone figure in the distance.",
            "3420": "A glitchy, distorted world where the laws of physics no longer apply. Shapes and colors warp and contort in impossible ways.",
            "3510": "A towering, futuristic cityscape that seems to go on forever, with flashing lights and neon signs as far as the eye can see.",
            "3600": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "3690": "A vast, empty space filled with slowly moving clouds of gas and dust.",
            "3780": "A strange, otherworldly landscape filled with bizarre rock formations and surreal vistas.",
            "3870": "A kaleidoscope of shapes and colors twisting and morphing into each other in a mesmerizing display.",
            "3960": "A dark, foreboding cave system, filled with strange, glowing crystals and ominous shadows.",
            "4050": "A shimmering, translucent ocean filled with strange, alien life forms.",
            "4140": "A chaotic, glitchy world where reality is constantly shifting and changing, and nothing can be trusted.",
            "4230": "A neon-colored rollercoaster that twists and turns through a futuristic cityscape.",
            "4320": "A pulsating, rhythmic mass of energy that seems to be moving in time with the music.",
            "4410": "A vast, empty space with a single object in the center - a glowing orb that seems to be drawing all the energy and light towards it.",
            "4500": "A psychedelic forest of towering, luminescent trees and strange, otherworldly creatures."
        }
    ],
    'music_name': 
        [
            'M000001',
            'M000002'    
        ],
    'n_frames_music':
        [   
            16,
            20          
        ]
}
