transcendence = {
    'image_generation':
    [
        {
           "0": "A pulsing, vibrant forest with trees and plants that seem to come to life in time with the music, suggesting the interconnectedness and interdependence of all living things",
"90": "A pulsating orb of light surrounded by geometric shapes and patterns, symbolizing the interconnectedness of all things",
"180": "A series of abstract, psychedelic visuals that morph and shift in time with the music, suggesting the impermanence of existence",
"270": "A surreal landscape of floating islands and cascading waterfalls, representing the beauty and wonder of the natural world",
"360": "An intricate maze of circuit boards and wires, hinting at the complexity of life and the systems that govern it",
"450": "A dark, foreboding labyrinth with mysterious symbols and sigils etched into the walls, suggesting the enigmatic nature of existence",
"540": "A pulsing, vibrant mandala made of light and color, symbolizing the infinite possibilities and potential of life",
"630": "A sprawling metropolis shrouded in fog and mystery, hinting at the hidden depths and secrets of the universe",
"720": "A mesmerizing, kaleidoscopic array of shapes and patterns that shift and dance in time with the music, suggesting the cyclical nature of life",
"810": "A barren wasteland of sand and dust, with a lone tree standing in the center as a symbol of hope and resilience",
"900": "A series of haunting, otherworldly landscapes that seem to exist in a realm beyond our own, suggesting the vastness and mystery of the cosmos",
"990": "A swirling vortex of energy and light, hinting at the power and transformative potential of the creative process",
"1080": "A series of glitchy, fragmented images that hint at the fleeting and ephemeral nature of existence",
"1170": "A monolithic structure rising out of a desolate plain, evoking feelings of awe and insignificance in the face of the universe",
"1260": "A pulsing, glowing sphere that seems to contain all of the knowledge and wisdom of the universe, inviting viewers to contemplate the meaning of life",
"1350": "A futuristic laboratory filled with strange and exotic machinery, suggesting the power of human ingenuity and innovation",
"1440": "A swirling vortex of fire and brimstone, evoking feelings of fear and uncertainty in the face of the unknown",
"1530": "A vast, star-filled expanse of space that stretches out to infinity, representing the endless possibilities and potential of existence",
"1620": "A series of vibrant, colorful landscapes that seem to pulsate with life and energy, inviting viewers to revel in the beauty of the world around them",
"1710": "A mysterious, ancient temple shrouded in mist and mystery, hinting at the deep history and cultural significance of human existence",
"1800": "A pulsing, living organism that seems to breathe and move in time with the music, symbolizing the interconnectedness of all living things",
"1890": "A series of abstract, geometric landscapes that shift and transform in time with the music, suggesting the impermanence and transience of existence",
"1980": "A stark, minimalist landscape with a single tree standing in the center, symbolizing the fragility and beauty of life",
"2070": "A series of dreamlike, surreal landscapes that exist in a realm beyond our own, inviting viewers to contemplate the mysteries of the universe",
"2160": "A pulsing, vibrant network of interconnected nodes and pathways, suggesting the complexity and interdependence of all things",
"2250": "A series of abstract, fractal-like patterns that seem to extend infinitely in all directions, evoking feelings of wonder and awe in the face of the infinite",
"2340": "A shimmering, ethereal realm filled with mystical symbols and strange, otherworldly creatures, suggesting the hidden depths and mysteries of the universe",
"2430": "A series of surreal, dreamlike landscapes that seem to blur the boundaries between reality and fantasy, inviting viewers to explore the inner reaches of their own minds",
"2520": "A vast, sprawling cityscape with towering skyscrapers and bustling streets, suggesting the endless possibilities and opportunities of modern life",
"2610": "A pulsating, glowing orb surrounded by a halo of light, symbolizing the transcendent nature of human consciousness and the search for meaning in life",
"2700": "A series of abstract, minimalist landscapes that evoke feelings of calm and serenity, inviting viewers to contemplate the beauty of simplicity",
"2790": "A swirling vortex of water and light, suggesting the fluidity and interconnectedness of all things in the universe",
"2880": "A series of abstract, futuristic cityscapes that seem to exist in a realm beyond our own, suggesting the infinite possibilities of human imagination",
"2970": "A stark, desolate landscape with a single, glowing object in the center, hinting at the power of focus and determination in the pursuit of one's goals",
"3060": "A series of abstract, geometric shapes that seem to come to life and dance in time with the music, suggesting the vibrancy and energy of the universe",
"3150": "A pulsing, glowing portal that seems to lead to another realm, inviting viewers to explore the mysteries of the unknown",
"3240": "A series of surreal, dreamlike landscapes that seem to shift and transform in time with the music, suggesting the fluidity and impermanence of existence",
"3330": "A vast, expansive ocean with a single, small boat sailing across the horizon, suggesting the power of human perseverance in the face of adversity",
"3420": "A series of abstract, otherworldly landscapes that seem to exist in a realm beyond our own, inviting viewers to contemplate the mysteries of the universe",
"3510": "A pulsing, vibrant forest with trees and plants that seem to come to life in time with the music, suggesting the interconnectedness and interdependence of all living things",
"3600": "A series of abstract, minimalist landscapes with a single, bright light shining in the center, suggesting the power of focus and determination in the pursuit of one's goals",
"3690": "A swirling vortex of light and color, suggesting the infinite possibilities and potential of existence",
"3780": "A series of abstract, geometric shapes that seem to come to life and dance in time with the music, inviting viewers to explore the vibrancy and energy of the universe",
"3870": "A stark, desolate landscape with a single, glowing object in the center, hinting at the power of focus and determination in the pursuit of one's goals",
"3960": "A series of surreal, dreamlike landscapes that seem to shift and transform in time with the music, suggesting the fluidity and impermanence of existence",
"4050": "A pulsing, glowing orb surrounded by a halo of light, symbolizing the transcendent nature of human consciousness and the search for meaning in life",
"4140": "A vast, expansive ocean with a single, small boat sailing across the horizon, suggesting the power of human perseverance in the face of adversity",
"4230": "A series of abstract, otherworldly landscapes that seem to exist in a realm beyond our own, inviting viewers to contemplate the mysteries of the universe",
"4320": "A shimmering, ethereal realm filled with mystical symbols and strange, otherworldly creatures, suggesting the hidden depths and mysteries of the universe",
"4410": "A pulsing, vibrant forest with trees and plants that seem to come to life in time with the music, suggesting the interconnectedness and interdependence of all living things",
"4500": "A series of abstract, fractal-like patterns that seem to extend infinitely in all directions, evoking feelings of wonder and awe in the face of the infinite."

        },
        {
"0": "An image of a newborn baby, representing the beginning of life and the infinite possibilities that lie ahead.",
"90": "A clock ticking away, symbolizing the fleeting nature of time and the importance of living in the present moment.",
"180": "A group of people huddled together in a circle, representing the power of community and the importance of human connection.",
"270": "A solitary figure standing on a mountaintop, representing the pursuit of personal growth and self-discovery.",
"360": "A person embracing their loved ones, symbolizing the importance of love and relationships in a fulfilling life.",
"450": "A bustling cityscape, representing the complexity and diversity of the human experience.",
"540": "A tree growing in a barren landscape, symbolizing the resilience of life and the power of hope.",
"630": "A person reaching towards the sun, representing the pursuit of higher ideals and a sense of purpose.",
"720": "A person walking through a maze, symbolizing the challenges and obstacles that one must overcome in order to find meaning in life.",
"810": "A butterfly emerging from a cocoon, representing the transformative power of growth and change.",
"900": "A person standing in front of a mirror, symbolizing the importance of self-reflection and understanding one's own identity.",
"990": "A vast expanse of stars and galaxies, representing the infinite possibilities of the universe and the interconnectedness of all things.",
"1080": "A person holding a seedling in their hands, symbolizing the potential for growth and new beginnings.",
"1170": "A person standing on the shore of an ocean, representing the vastness and mystery of the natural world.",
"1260": "A person meditating in front of a waterfall, symbolizing the importance of inner peace and mindfulness.",
"1350": "A person standing in the middle of a field, surrounded by nature, representing the simplicity and beauty of a life lived in harmony with the earth.",
"1440": "A person holding a book, symbolizing the power of knowledge and the importance of lifelong learning.",
"1530": "A group of people gathered around a fire, representing the power of storytelling and the importance of passing on wisdom to future generations.",
"1620": "A person dancing in a crowded nightclub, representing the joy and energy of the human spirit.",
"1710": "A person standing in front of a blank canvas, symbolizing the potential for creativity and self-expression.",
"1800": "A person walking towards a distant horizon, representing the pursuit of new horizons and a life of adventure.",
"1890": "A person standing on a mountaintop at sunrise, symbolizing the beauty and majesty of the natural world.",
"1980": "A person hugging a friend or family member, representing the importance of human connection and emotional support.",
"2070": "A person standing in the rain, symbolizing the importance of resilience and finding beauty in difficult times.",
"2160": "A person standing in front of a city skyline at night, representing the excitement and energy of urban life.",
"2250": "A person playing an instrument, symbolizing the power of music to evoke emotions and bring people together.",
"2340": "A person sitting alone in a quiet room, representing the importance of introspection and finding inner peace.",
"2430": "A person standing in a field of flowers, symbolizing the beauty and abundance of the natural world.",
"2520": "A person reaching out to help someone in need, representing the importance of kindness and compassion in building a meaningful life.",
"2610": "A person standing in front of a mirror, looking at their reflection with self-acceptance and self-love.",
"2700": "A person walking on a tightrope, symbolizing the balance and perseverance required to navigate life's challenges.",
"2790": "A person standing on a beach, watching the waves crash on the shore, representing the power and beauty of nature.",
"2880": "A person holding a newborn baby, symbolizing the continuity of life and the importance of passing on love and knowledge to future generations.",
"2970": "A person standing in front of a mountain, representing the power and majesty of nature and the importance of striving for greatness.",
"3060": "A person running through a crowded city street, representing the energy and vitality of urban life.",
"3150": "A person holding a compass, symbolizing the importance of setting goals and following one's own path.",
"3240": "A person standing in front of a mirror, making silly faces and laughing, representing the importance of joy and lightheartedness in life.",
"3330": "A person standing in the rain, holding an umbrella and feeling a sense of peace and calm.",
"3420": "A person holding hands with a loved one, symbolizing the importance of human connection and support in navigating life's challenges.",
"3510": "A person standing in front of a brick wall, breaking it down with a sledgehammer, representing the power of determination and perseverance in achieving one's goals.",
"3600": "A person standing on a mountaintop at sunset, feeling a sense of accomplishment and awe at the beauty of the world."
},
        {
"0": "A barren landscape, with only rocks and dust visible.",
"90": "A single seedling sprouting from the ground, struggling to survive.",
"180": "The plant has grown into a lush oasis, with wildlife gathering around it.",
"270": "A humanoid figure emerges from the foliage, looking around in wonder.",
"360": "The humanoid discovers fire and begins to use it for warmth and protection.",
"450": "The humanoid develops tools and begins to build shelter and create art.",
"540": "The humanoid forms a community, sharing knowledge and skills.",
"630": "The community faces challenges, but works together to overcome them.",
"720": "The community advances technologically, developing machines and infrastructure.",
"810": "The machines become more complex, and the community becomes reliant on them.",
"900": "The community begins to explore beyond their borders, encountering other cultures.",
"990": "The community learns from these cultures, and integrates their knowledge and ideas.",
"1080": "The community faces a crisis, and must come together to solve it.",
"1170": "The crisis is overcome, but the community is forever changed by the experience.",
"1260": "The community turns their attention to the stars, and begins to dream of space travel.",
"1350": "The community builds rockets and launches them into orbit.",
"1440": "The community sends their first astronauts into space, and watches in awe as they explore the cosmos.",
"1530": "The community builds a space station, and begins to conduct experiments in zero gravity.",
"1620": "The community establishes a colony on the moon, and begins to mine its resources.",
"1710": "The community sends a mission to Mars, and begins to terraform the planet.",
"1800": "The community discovers evidence of extraterrestrial life, and begins to study it.",
"1890": "The community encounters a hostile alien race, and must defend itself.",
"1980": "The community forms alliances with other alien races, and establishes a galactic federation.",
"2070": "The federation explores the far reaches of the universe, encountering wonders beyond imagination.",
"2160": "The federation discovers a way to transcend physical form, and becomes a purely spiritual entity.",
"2250": "The spiritual entity begins to explore the mysteries of the universe on a whole new level.",
"2340": "The entity discovers that the universe is a simulation, and begins to manipulate it.",
"2430": "The entity creates its own universe, and becomes the god of its own creation.",
"2520": "The entity begins to question the nature of reality, and wonders if there is something beyond even its own existence.",
"2610": "The entity discovers a higher plane of existence, and merges with it.",
"2700": "The entity becomes part of a vast, interconnected network of consciousness, spanning the entire multiverse.",
"2790": "The entity realizes that its journey of evolution is never-ending, and that there is always more to discover and explore.",
"2880": "The entity continues to evolve and expand, transcending even the boundaries of time and space.",
"2970": "The entity finally reaches the ultimate state of being, and becomes one with the infinite.",
"3060": "A moment of silence, as the music fades away.",
"3150": "The screen fades to black.",
"3240": "The music slowly starts to build again.",
"3330": "A beat drops, and the screen flashes to life with a burst of energy.",
"3420": "The words 'Evolution is Infinite ' appear on the screen in bold letters.",
"3510": "The music becomes more intense, and the screen is filled with pulsating lights and psychedelic imagery.",
"3600": "The video ends with a final burst of energy, leaving the viewer in awe of the infinite possibilities of evolution and the power of techno music to tell stories that transcend time and space."
},


    ],
    'music_name': 
        [
            'transcendence',
            'life',
            'evolution',
        ],
    'n_frames_music':
        [   
            150,
            150,
            150,
        ]
}