jack_jewel = {
         "text_spoken": 
         {
         "0": "Once upon a time, in a small town nestled in the heart of the countryside, there lived a young boy named Jack.",
         "1": "Jack was a curious and adventurous boy, always eager to explore and discover new things.",
         "2": "One day, while wandering through the fields and forests surrounding his home, he stumbled upon a strange and curious situation.",
         "3": "As the boy was walking, he heard a faint buzzing noise in the distance.",
         "4": "As little Jack followed the sound, he came upon a clearing in the forest where he saw a group of bees gathered around a small pond.",
         "5": "But as the child approached, he realized that these were not ordinary bees.",
         "6": "The bees were larger and had a bright, iridescent sheen to their bodies.",
         "7": "Jack was fascinated by these strange bees and decided to investigate further.",
         "8": "As the boy approached the pond, he noticed that the bees were not collecting nectar from flowers, but instead, they were diving into the water and emerging with small, sparkling jewels in their claws.",
         "9": "Intrigued, Jack decided to take a closer look.",
         "10": "The child slowly made his way to the edge of the pond and peered in.",
         "11": "To his amazement, Jack saw that the bottom of the pond was covered in a thick layer of glittering jewels.",
         "12": "He could not believe his eyes.",
         "13": "He had discovered a hidden treasure trove of precious gems and jewels.",
         "14": "Without hesitation, Jack plunged into the water and began to collect as many jewels as he could.",
         "15": "The bees, however, were not happy with this intrusion and began to buzz around him, trying to protect their treasure.",
         "16": "But Jack was determined and managed to collect a small handful of jewels before the bees chased him out of the clearing.",
         "17": "Breathless and soaked, Jack returned home with his precious jewels.",
         "18": "He showed them to his family and friends, and soon the news of his discovery spread throughout the town.",
         "19": "Word of Jack's discovery reached the ears of a wealthy jeweler who was passing through the town.",
         "20": "The jeweler was so impressed by the quality of the jewels that he offered to buy them all from Jack.",
         "21": "And so, with the money he earned, Jack was able to start his own business and became a successful jeweler himself.",
         "22": "From that day on, Jack never forgot the strange and curious situation he had stumbled upon in the forest.",
         "23": "And he always remembered the bees that had guarded their treasure so fiercely, for they had helped him to make his dreams come true.",
            },

         "image_generation": {
            "0": "young boy named boy, small town nestled, upon, time, lived, heart, countryside",
            "1": "discover new things, always eager, adventurous boy, boy, explore, curious",
            "2": "stumbled upon, one day, forests surrounding, curious situation, wandering, strange, home, fields",
            "3": "faint buzzing noise, walking, heard, distance, boy",
            "4": "((bees)) (((small pond))), forest",
            "5": "bees iridescent sheen, larger, bright,",
            "6": "bees iridescent sheen, larger, bright, ",
            "7": "strange bees, boy, investigate, fascinated, decided",
            "8": "((sparkling jewels)), collecting nectar, water, (((small pond))), noticed, instead, flowers, emerging, diving, claws, bees",
            "9": "((sparkling jewels)), collecting nectar, water, (((small pond))), noticed, instead, flowers, emerging, diving, claws, bees",
            "10": "((sparkling jewels)), collecting nectar, water, (((small pond))), noticed, instead, flowers, emerging, diving, claws, bees",
            "11": "thick layer, boy saw, glittering jewels, pond, covered, bottom, amazement",
            "12": "eyes, could, believe",
            "13": "hidden treasure trove, precious gems, jewels, discovered",
            "14": "boy dive water to get gems bees running after boy",
            "15": "buzz around, trying, treasure, protect, intrusion, however, happy, began, bees",
            "16": "small handful, bees chased, managed, jewels, boy, determined, collect, clearing",
            "17": "boy returned home with precious jewels",
            "18": "boy returned home with precious jewels",
            "19": "man, wealthy jeweler,",
            "20": "quality, offered, jewels, jeweler, boy, impressed, buy",
            "21": "successful jeweler, start, money, boy, earned, business, became, able",
            "22": "boy never forgot, stumbled upon, curious situation, strange, forest, day",
            "23": "dreams come true, always remembered, treasure, make, helped, guarded, fiercely, bees",
}
}

        